name: PR Checks

on:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      node-version: ${{ steps.setup-node.outputs.node-version }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js from package.json
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ steps.setup-node.outputs.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ steps.setup-node.outputs.node-version }}-

  type-check:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ needs.setup.outputs.node-version }}

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ needs.setup.outputs.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ needs.setup.outputs.node-version }}-

      - name: Install dependencies
        run: npm ci

      - name: Type Check
        run: npm run type-check

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ needs.setup.outputs.node-version }}

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ needs.setup.outputs.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ needs.setup.outputs.node-version }}-

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ needs.setup.outputs.node-version }}

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ needs.setup.outputs.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ needs.setup.outputs.node-version }}-

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

  publint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ needs.setup.outputs.node-version }}

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ needs.setup.outputs.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ needs.setup.outputs.node-version }}-

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publint
        run: npm run publint

concurrency:
  group: pr-${{ github.head_ref }}
  cancel-in-progress: true
